# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0005_auto_20161124_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='menu',
            field=models.ForeignKey(choices=[(1, '黑胶牛仔骨 + 蒜蓉炒空心菜')], on_delete=django.db.models.deletion.CASCADE, related_name='exchange_menu', to='CSS.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 24, 23, 41, 25, 233276, tzinfo=utc)),
        ),
    ]
