# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0007_auto_20161124_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='CSS/images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 0, 15, 53, 123038, tzinfo=utc)),
        ),
    ]
