# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0009_auto_20161124_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='menu',
            field=models.ForeignKey(choices=[(1, '黑胶牛仔骨 + 蒜蓉炒空心菜'), (4, '水煮鱼 + 白灼芥蓝')], on_delete=django.db.models.deletion.CASCADE, related_name='exchange_menu', to='CSS.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='CSS/images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 0, 29, 55, 246448, tzinfo=utc)),
        ),
    ]
