# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0011_auto_20161124_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('image', models.ImageField(upload_to='CSS/images/locations')),
                ('googleMap', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 1, 39, 2, 190752, tzinfo=utc)),
        ),
    ]
