# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0012_auto_20161124_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='googleMap',
            new_name='googleMapURL',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 2, 5, 18, 985585, tzinfo=utc)),
        ),
    ]
