# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0014_auto_20161124_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 2, 57, 23, 148528, tzinfo=utc)),
        ),
    ]
