# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0019_auto_20161125_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='menu',
        ),
        migrations.AddField(
            model_name='location',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='CSS.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 22, 35, 14, 493099, tzinfo=utc)),
        ),
    ]
