# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0022_auto_20161127_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 27, 14, 58, 9, 75027, tzinfo=utc)),
        ),
    ]
