# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0025_auto_20161127_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to='CSS/images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 2, 55, 59, 23843, tzinfo=utc)),
        ),
    ]
