# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0030_auto_20161128_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='contact',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exchange',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='location',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='menu',
            field=models.ForeignKey(choices=[(8, '炸鸡排'), (10, '炒年糕'), (11, '卤肉饭'), (9, '泰式鱼片')], on_delete=django.db.models.deletion.CASCADE, related_name='exchange_menu', to='CSS.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 19, 48, 24, 70142, tzinfo=utc)),
        ),
    ]
