# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSS', '0031_auto_20161129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_menu', to='CSS.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CSS/images/menus'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 1, 0, 37, 328347, tzinfo=utc)),
        ),
    ]
